#!/usr/bin/env bash
# Vendors C++ source into bindings/go/ for use as a self-contained Go module.
#
# Source of truth: third_party/longfellow-zk submodule (pinned by git) + src/ + include/.
# Run after bumping the submodule or editing src/. CI enforces no-drift via:
#   ./scripts/sync-go-bindings.sh && git diff --exit-code bindings/go/
#
# The script is intentionally explicit (one cp per file) so that
# `grep cp scripts/sync-go-bindings.sh` shows exactly what gets vendored.

set -euo pipefail

cd "$(dirname "$0")/.."

LF_DIR="third_party/longfellow-zk"
LF_LIB="${LF_DIR}/lib"
DST="bindings/go"
DST_LF="${DST}/third_party/longfellow-zk"
PATCH_DIR="patches/longfellow-zk"

if [[ ! -d "${LF_LIB}" ]]; then
  echo "error: ${LF_LIB} missing — run: git submodule update --init ${LF_DIR}" >&2
  exit 1
fi

# Locate OpenSSL headers so the clang -MM dependency walk can resolve <openssl/...>.
if [[ "$(uname)" == "Darwin" ]]; then
  OPENSSL_INC="/opt/homebrew/opt/openssl@3/include"
elif command -v pkg-config >/dev/null 2>&1 && pkg-config --exists openssl 2>/dev/null; then
  OPENSSL_INC="$(pkg-config --variable=includedir openssl)"
else
  OPENSSL_INC="/usr/include"
fi

if [[ ! -f "${OPENSSL_INC}/openssl/sha.h" ]]; then
  echo "error: OpenSSL headers not found at ${OPENSSL_INC}/openssl/sha.h" >&2
  echo "       install libssl-dev (Linux) or openssl@3 via Homebrew (macOS)" >&2
  exit 1
fi

# Capture the exact upstream commit we're vendoring from.
LF_COMMIT="$(git -C "${LF_DIR}" rev-parse HEAD)"
LF_SHORT="$(git -C "${LF_DIR}" rev-parse --short HEAD)"
LF_DESCRIBE="$(git -C "${LF_DIR}" describe --always --dirty)"

# 1. Wipe previous vendor (keeps directory layout deterministic, no stale files).
rm -rf "${DST}"/cxx_*.cc "${DST}/include" "${DST_LF}"
mkdir -p "${DST}/include/attested_key_zk" "${DST_LF}/lib"

# 2. Copy public C header (consumer-visible API surface).
cp "include/attested_key_zk/approval_proof_v1_zk.h" \
   "${DST}/include/attested_key_zk/approval_proof_v1_zk.h"

# 3. Copy our own C++ source. Flat at package root so cgo auto-compiles it.
cp "src/approval_proof_v1_zk.cc" \
   "${DST}/cxx_approval_proof_v1_zk.cc"

# 4. Copy each Longfellow .cc — explicit per-file so the mapping is grep-able.
#    Renamed with cxx_lf_<dir>_<name>.cc so they sit flat at the package root
#    without colliding (cgo only auto-compiles files at the root, not subdirs).
cp "${LF_LIB}/util/log.cc"                          "${DST}/cxx_lf_util_log.cc"
cp "${LF_LIB}/util/crypto.cc"                       "${DST}/cxx_lf_util_crypto.cc"
cp "${LF_LIB}/algebra/nat.cc"                       "${DST}/cxx_lf_algebra_nat.cc"
cp "${LF_LIB}/algebra/crt.cc"                       "${DST}/cxx_lf_algebra_crt.cc"
cp "${LF_LIB}/ec/p256.cc"                           "${DST}/cxx_lf_ec_p256.cc"
cp "${LF_LIB}/circuits/sha/flatsha256_witness.cc"   "${DST}/cxx_lf_circuits_sha_flatsha256_witness.cc"
cp "${LF_LIB}/circuits/sha/sha256_constants.cc"     "${DST}/cxx_lf_circuits_sha_sha256_constants.cc"

# 5. Compute transitive header closure with clang -MM and copy each header,
#    preserving its relative path under bindings/go/third_party/longfellow-zk/lib/.
#    Run -MM against the just-copied flat .cc files using the same -I flags the
#    cgo build will use, so what we vendor is exactly what the consumer compiles.
HEADERS_RAW="$(clang++ -std=c++17 -MM \
  -DOPENSSL_SUPPRESS_DEPRECATED=1 \
  -I "${LF_LIB}" \
  -I "include" \
  -I "${OPENSSL_INC}" \
  "${DST}"/cxx_*.cc 2>/dev/null)"

# clang -MM emits a Make rule: "target.o: file1 file2 \\\n  file3 file4". Strip
# the target, line-continuations, and whitespace; keep only paths under LF_LIB.
HEADERS="$(printf '%s\n' "${HEADERS_RAW}" \
  | sed -e 's/[a-zA-Z0-9_.-]*\.o://' -e 's/\\$//' \
  | tr -s '[:space:]' '\n' \
  | grep -E "^${LF_LIB}/.*\.(h|hh|hpp|inc)$" \
  | sort -u)"

if [[ -z "${HEADERS}" ]]; then
  echo "error: clang -MM produced no Longfellow headers — check include paths" >&2
  exit 1
fi

HEADER_COUNT=0
while IFS= read -r h; do
  rel="${h#${LF_LIB}/}"
  install -d "${DST_LF}/lib/$(dirname "${rel}")"
  cp "${h}" "${DST_LF}/lib/${rel}"
  HEADER_COUNT=$((HEADER_COUNT + 1))
done <<< "${HEADERS}"

# 6. Vendor the upstream LICENSE (Apache 2.0 §4 attribution).
cp "${LF_DIR}/LICENSE" "${DST_LF}/LICENSE"

# 7. Apply repo-local vendor patches. These are limited to the Go binding's
#    vendored snapshot; the submodule remains pinned to upstream Longfellow.
PATCH_PROVENANCE=$'\nNone.'
if [[ -d "${PATCH_DIR}" ]]; then
  PATCH_LIST="$(find "${PATCH_DIR}" -maxdepth 1 -type f -name '*.patch' | sort)"
  if [[ -n "${PATCH_LIST}" ]]; then
    PATCH_PROVENANCE=""
    while IFS= read -r patch; do
      git apply --directory="${DST_LF}" "${patch}"
      PATCH_PROVENANCE+=$'\n'"- \`${patch}\`"
    done <<< "${PATCH_LIST}"
  fi
fi

# 8. Write provenance manifest with exact commit + file mapping.
cat > "${DST}/PROVENANCE.md" <<EOF
# Vendor Provenance

Generated by \`scripts/sync-go-bindings.sh\` — do not edit by hand.

The C++ sources under this directory are a snapshot copy from the
\`third_party/longfellow-zk\` git submodule and our own \`src/\`. The submodule
remains the source of truth; repo-local patches under \`${PATCH_DIR}/\` are
applied after vendoring. To upgrade, check out a new submodule commit there and
re-run \`./scripts/sync-go-bindings.sh\`.

## Upstream

- Repository: \`third_party/longfellow-zk\` git submodule
- Commit:    \`${LF_COMMIT}\`
- Short:     \`${LF_SHORT}\`
- Describe:  \`${LF_DESCRIBE}\`

## File mapping (upstream → vendored)

| Upstream path | Vendored path |
|---|---|
| \`include/attested_key_zk/approval_proof_v1_zk.h\` | \`bindings/go/include/attested_key_zk/approval_proof_v1_zk.h\` |
| \`src/approval_proof_v1_zk.cc\` | \`bindings/go/cxx_approval_proof_v1_zk.cc\` |
| \`${LF_LIB}/util/log.cc\` | \`bindings/go/cxx_lf_util_log.cc\` |
| \`${LF_LIB}/util/crypto.cc\` | \`bindings/go/cxx_lf_util_crypto.cc\` |
| \`${LF_LIB}/algebra/nat.cc\` | \`bindings/go/cxx_lf_algebra_nat.cc\` |
| \`${LF_LIB}/algebra/crt.cc\` | \`bindings/go/cxx_lf_algebra_crt.cc\` |
| \`${LF_LIB}/ec/p256.cc\` | \`bindings/go/cxx_lf_ec_p256.cc\` |
| \`${LF_LIB}/circuits/sha/flatsha256_witness.cc\` | \`bindings/go/cxx_lf_circuits_sha_flatsha256_witness.cc\` |
| \`${LF_LIB}/circuits/sha/sha256_constants.cc\` | \`bindings/go/cxx_lf_circuits_sha_sha256_constants.cc\` |
| \`${LF_LIB}/<header>\` (transitive closure via \`clang -MM\`) | \`bindings/go/third_party/longfellow-zk/lib/<header>\` |
| \`${LF_DIR}/LICENSE\` | \`bindings/go/third_party/longfellow-zk/LICENSE\` |

## Header closure size

${HEADER_COUNT} headers vendored from \`${LF_LIB}\`.

## Local patches
${PATCH_PROVENANCE}
EOF

echo "vendored from longfellow-zk @ ${LF_SHORT} (${LF_DESCRIBE}); ${HEADER_COUNT} headers"
